# Site
name: "한 단계 더 위로"
title: "한 단계 더 위로"
description: "jyukki's blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /study
disqus: 'jyukki97'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  jyukki:
    name: jyukki
    display_name: jyukki
    # gravatar: e56154546cf4be74e393c62d1ae9f9d4
    avatar: 'assets/images/1623854336046.jpg'
    email: jyukki97@gmail.com
    web: https://jyukki97.github.io/
    description: "오늘보다 한단계 더 위로"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
